version: '2.1'

services:

  users-db:
    container_name: users-db
    build: ./project/db
    ports: 
      - 5435:5432 # expose ports - HOST:CONTAINER
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck: 
      test: exit 0

  users-service:
    container_name: users-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      